name: React Frontend CI/CD - Azure Static Web App

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy
  displayName: Build and Deploy React App
  condition: |
    or(
      eq(variables['Build.Reason'], 'Manual'),
      eq(variables['Build.Reason'], 'PullRequest'),
      eq(variables['Build.Reason'], 'IndividualCI')
    )
  pool:
    vmImage: ubuntu-latest

  variables:
    - group: Azure-Static-Web-App-Variable-Group  # 👈 Your variable group name with deployment token

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'  # 👈 Use your React project's Node.js version
      displayName: 'Install Node.js'

    - checkout: self

    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build React app'

    - task: AzureStaticWebApp@0
      inputs:
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
        app_location: '/'              # 👈 Location of React app (where package.json is)
        api_location: ''               # 👈 Leave empty if no backend API
        output_location: 'build'       # 👈 Output folder after build (React = build)
